app/controllers/roadtrips_controller.rb
app/models/roadtrip.rb
app/views/roadtrips/edit.html.erb
app/views/roadtrips/index.html.erb
app/views/roadtrips/new.html.erb
app/views/roadtrips/show.html.erb
config/routes.rb
db/migrate/20210824120507_create_roadtrips.rb
db/schema.rb
test/controllers/roadtrips_controller_test.rb
test/models/roadtrip_test.rb

Add controller + model + view roadtrip

controllers + model roadtrip

---

app/views/roadtrips/index.html.erb
db/migrate/20210824155259_add_status_to_roadtrips.rb

pensez à db drop create et migrate

reset migration

---

app/javascript/components/initmap.js
app/javascript/packs/application.js
app/views/itineraries/show.html.erb

- Création des directions entre les markeurs
- Actuellement seulement possible de créer 3 steps

mapdirectionupdate

---

app/javascript/components/initmap.js

- Direction multiple steps done

directiondone

---

app/javascript/components/roadtripsindex.js
app/javascript/packs/application.js
app/views/friendships/index.html.erb
app/views/shared/_navbar.html.erb

Front checklist

---

app/javascript/components/roadtripsindex.js

filtres qui fonctionnent

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_roadtrips.scss
app/views/pages/home.html.erb
app/views/roadtrips/index.html.erb

Ajout media queries home page + index des trips(pas fini car totof boss sur la page)

add media queries

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_checklist.scss
app/assets/stylesheets/pages/_roadtrip_show.scss
app/views/roadtrips/show.html.erb

Ajout media queries sur show road trips

ajout media queries sur show roadtrip

---

app/views/roadtrips/show.html.erb

Fix wrong image displaying on roadtrip show

Fix image display

---

app/assets/stylesheets/components/_card.scss
app/views/roadtrips/index.html.erb
app/views/roadtrips/show.html.erb

Changement des font awesome, 
changement des couleurs 
Changement de côté du triangle;

Front card

---

app/assets/stylesheets/pages/_roadtrip_show.scss
app/views/roadtrips/show.html.erb

ajout de la date en haut a droite de show trip

ajout de la date sur show trip

---

app/views/devise/registrations/edit.html.erb

Done translate profil

---

app/assets/stylesheets/pages/_showmap.scss
app/javascript/components/initmap.js
app/javascript/packs/application.js
app/views/itineraries/show.html.erb

fixbug0step

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_list.scss
app/assets/stylesheets/pages/_checklist.scss
app/assets/stylesheets/pages/_roadtrip_show.scss
app/controllers/itineraries_controller.rb
app/controllers/roadtrips_controller.rb
app/views/roadtrips/show.html.erb
app/views/shared/_navbar.html.erb

Frontshowroadtrip

---

app/assets/stylesheets/pages/_home.scss
app/javascript/plugins/flatpickr.js
app/views/pages/home.html.erb

ajout des 3 derniers road trips sur l'home page et 3 icons fb insta github en footer

Modif homepage

---

app/controllers/partners_controller.rb
app/views/partners/new.html.erb
app/views/roadtrips/show.html.erb

Clean des comments que j'ai laissé

cleans les comments

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_modalmessagerie.scss
app/channels/roadtrip_channel.rb
app/controllers/messages_controller.rb
app/javascript/channels/roadtrip_channel.js
app/javascript/components/activeButton.js
app/javascript/components/textarea_enter_key.js
app/javascript/packs/application.js
app/views/messages/_message.html.erb
app/views/shared/_modalmessagerie.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

-Fix du Bug de la messagerie quand il utilisait le params[:id] du RoadtripController au lieu du params[:room]
-Ajouter bouton active quand la room est selectionné
-Bouton log out changé en Déconnexion
-Fix du bug qui à l'envoie d'un message duplique le params
-Ajout un fond plus sombre derrière la modal
-Mise a jour du style des messages
-Ajout d'ActionCable
-Ajouter la touche Entrer à l'envoie du message

Modal improvement

---

app/views/pages/home.html.erb

fixbugnosign

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/pages/_partnersnew.scss
app/javascript/components/partnersnew.js
app/javascript/packs/application.js
app/views/partners/new.html.erb
db/seeds.rb

Seed pour la demo 
ajout d'un peu de front sur les partners
correction d'un bug JS partner

Partnernewsfront

---

db/seeds.rb

add photo seed

---

app/views/partners/new.html.erb

Colors button, delete h2 newpartner

add colors

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_modalmessagerie.scss
app/views/roadtrips/index.html.erb
app/views/shared/_modalmessagerie.html.erb

Custom roadtrip index

---

app/assets/stylesheets/components/_card.scss
app/views/devise/registrations/edit.html.erb
app/views/roadtrips/index.html.erb

-Delete supprimer bouton
-Translate alert when delete a roadtrip in french
-spacing trash and eye on self card

Fix multipages
